[alias]
cli = "run --config .cargo/cli.toml --quiet --no-default-features --features cli --bin opencut --"
editor-mac = "run --config .cargo/macos.toml --no-default-features --features editor --bin opencut-editor"
editor-win = "run --config .cargo/windows.toml --no-default-features --features editor --bin opencut-editor"
test-mac = "test --config .cargo/macos.toml"
test-win = "test --config .cargo/windows.toml"
player-mac = "run --config .cargo/macos.toml --no-default-features --features player --bin opencut-player"
player-win = "run --config .cargo/windows.toml --no-default-features --features player --bin opencut-player"
build-editor-mac = "build --config .cargo/macos.toml --no-default-features --features editor --bin opencut-editor"
build-editor-win = "build --config .cargo/windows.toml --no-default-features --features editor --bin opencut-editor"
build-player-mac = "build --config .cargo/macos.toml --no-default-features --features player --bin opencut-player"
build-player-win = "build --config .cargo/windows.toml --no-default-features --features player --bin opencut-player"
mp3-mac = "run --config .cargo/macos.toml --no-default-features --features mp3 --bin mp3"
mp3-win = "run --config .cargo/windows.toml --no-default-features --features mp3 --bin mp3"
mp4-mac = "run --config .cargo/macos.toml --no-default-features --features mp4 --bin mp4"
mp4-win = "run --config .cargo/windows.toml --no-default-features --features mp4 --bin mp4"
mp4-v2-mac = "run --config .cargo/macos.toml --no-default-features --features mp4 --bin mp4-v2"
mp4-v2-win = "run --config .cargo/windows.toml --no-default-features --features mp4 --bin mp4-v2"
2win-mac = "run --config .cargo/macos.toml --quiet --no-default-features --features 2windows --bin 2windows"
2win-win = "run --config .cargo/windows.toml --quiet --no-default-features --features 2windows --bin 2windows"
loc = "run --quiet --no-default-features --bin loc"


[build]
target-dir = "target"
