[package]
name = "player-ui"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
engine.workspace = true
media-backend.workspace = true
timeline.workspace = true
anyhow.workspace = true
cpal.workspace = true
ffmpeg-next.workspace = true
futures.workspace = true
gpui.workspace = true
image.workspace = true
